### ISSUE TITLE
Cannot run PGAP with SElinux enabled

### ISSUE THREAD

**Issue by TheBigFatTony** [ncbi/pgap#10]
I tried to `./pgap --update` and got an error: `urllib.error.HTTPError: HTTP Error 403: Forbidden`

It was caused by bot being able to access https://s3.amazonaws.com/pgap/input-2019-02-11.build3477.tgz where I got `AccessDeniedAccess Denied5EA3714DAAA8A19BDUHYHrIjJGmuwWTapQA5YS1gsPPSBs81+EwRqg6F7bQMu/UTwi6XHga+G7h1OoYHwZv3USdhDCo=`

What went wrong?

#Edit: I tried it from my station in Switzerland as well as via a US-VPN.

**Comment by slottad** [comment]
Ah, my fault. You are using the development version of the pgap.py script, which is not yet ready for prime time. You are doing this because the wiki erroneously tells you to do so. Please use the release version instead:

`curl -OL https://github.com/ncbi/pgap/releases/download/2019-02-11.build3477/pgap.py`

I will update the wiki to the correct location. Sorry for the confusion.

**Comment by TheBigFatTony** [comment]
Please note somewhere (Qickstart/Installation?) that one has to create a Python3-venv and install `cwltool` and `cwlref-runner`.

After running `./pgap.py --update`, I got this error when I tried to test pgap (`/pgap.py -r test_genomes/MG37/input.yaml`):

```
/home/thomas/PycharmProjects/venvs/PGAP/bin/cwl-runner 1.0.20190228155703
/usr/bin/cwltool 1.0.20181217162649
Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
Tool definition failed initialization:
[Errno 13] Permission denied: '/pgap/user_input/pgap_input.yaml'
```

I assume this was because there was no `pgap-2019-02-11.build3477`-folder. I made it by running the `install_cwl`-method. Also, looking at the code, I supposed that there should be a link `pgap -> pgap-2019-02-11.build3477`, which I made. Then, I got this error:

```
/home/thomas/PycharmProjects/venvs/PGAP/bin/cwl-runner 1.0.20190228155703
/usr/bin/cwltool 1.0.20181217162649
Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
Tool definition failed initialization:
[Errno 13] Permission denied: '/pgap/user_input/pgap_input.yaml'
Traceback (most recent call last):
  File "./pgap.py", line 276, in <module>
    main()
  File "./pgap.py", line 273, in main
    run(version, input, args.output, debug)
  File "./pgap.py", line 227, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'run', '-i', '--user', '1000:1000', '--volume', '/home/thomas/PGAP_docker/input-2019-02-11.build3477:/pgap/input:ro', '--volume', '/home/thomas/PGAP_docker/test_genomes/MG37:/pgap/user_input', '--volume', '/home/thomas/PGAP_docker/output/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro', '--volume', '/home/thomas/PGAP_docker/output:/pgap/output:rw', '--volume', '/home/thomas/PGAP_docker/output/log:/log/srv', 'ncbi/pgap:2019-02-11.build3477', 'cwltool', '--outdir', '/pgap/output', 'pgap.cwl', '/pgap/user_input/pgap_input.yaml']' returned non-zero exit status 1.
```

Wtf went wrong?!

**Comment by slottad** [comment]
I did. I went wrong again. That pgap.py was too old. The previous one was too new. Hopefully, this new one is just right. I have actually tested it this time, and it should be.  

Please update your pgap.py once again, using the same curl command as above:

`curl -OL https://github.com/ncbi/pgap/releases/download/2019-02-11.build3477/pgap.py`

and then run your test once more.  You will need to move or delete your previous `output` directory.

So sorry about this, we have a new release coming out in a few weeks that should be much easier to use.

**Comment by slottad** [comment]
Oh, there should be no need for the Python virtual environment, everything should run under the docker container.  The old version used the `-r` flag to mean 'use a local runner' which never worked well, and that functionality is being removed.

**Comment by TheBigFatTony** [comment]
It still doesn't work. This time I ran `./pgap.py test_genomes/MG37/input.yaml`.

```
❯ python3 pgap.py -r test_genomes/MG37/input.yaml
/usr/bin/cwltool 1.0.20181217162649
Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
Tool definition failed initialization:
[Errno 13] Permission denied: '/pgap/user_input/pgap_input.yaml'
Traceback (most recent call last):
  File "pgap.py", line 293, in <module>
    main()
  File "pgap.py", line 290, in main
    run(version, input, args.output, debug, report)
  File "pgap.py", line 229, in run
    subprocess.check_call(cmd)
```

- Again, pgap.py seems to assume that there is a folder `pgap`, so I made a link `pgap-2019-02-11.build3477 -> pgap`. Ist that correct?
- However, in `pgap-2019-02-11.build3477`, there isn't a `user_input` folder anyway so the error stays the same.

Can you **please** send me a version that you've tested beforehand? I'm wasting a lot of time here.

**Comment by slottad** [comment]
Well this one is not my fault. I did test it beforehand. However, I tried again on on my home computer as well, and recreated your issue.

I have uploaded a new pgap.py with another fix. Please download it again, and try once more.

**Comment by TheBigFatTony** [comment]
i tried
`https://github.com/ncbi/pgap/releases/download/2019-02-11.build3477/pgap.py`
and got:
```
/usr/bin/cwltool 1.0.20181217162649
Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
Tool definition failed initialization:
[Errno 13] Permission denied: '/pgap/user_input/pgap_input.yaml'
Traceback (most recent call last):
  File "pgap.py", line 289, in <module>
    main()
  File "pgap.py", line 286, in main
    run(version, input, args.output, debug, report)
  File "pgap.py", line 230, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'run', '-i', '--user', '1000:1000', '--volume', '/home/username/PGAP_docker/input-2019-02-11.build3477:/pgap/input:ro', '--volume', '/home/username/PGAP_docker/test_genomes/MG37:/pgap/user_input', '--volume', '/home/username/PGAP_docker/output/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro', '--volume', '/home/username/PGAP_docker/output:/pgap/output:rw', '--volume', '/home/username/PGAP_docker/output/log:/log/srv', 'ncbi/pgap:2019-02-11.build3477', 'cwltool', '--outdir', '/pgap/output', 'pgap.cwl', '/pgap/user_input/pgap_input.yaml']' returned non-zero exit status 1.
```
although this time, it downloaded everything as expected i think.

**Comment by TheBigFatTony** [comment]
I tried again today, it seems nothing was changed and the error persists.

**Comment by slottad** [comment]
I'm sorry for all of the trouble you've had. We are in the midst of putting out a new release this week, and it is organized differently. It looks like this interferes with the old setup.

Please wait for the new release, which we hope will be much improved. We will let you know as soon as it is ready. 

Thank you for your patience and understanding.

**Comment by TheBigFatTony** [comment]
Thanks for the update!

**Comment by slottad** [comment]
There is a new release, check out https://github.com/ncbi/pgap/wiki/Quick-Start for updated instructions.

**Comment by azat-badretdin** [comment]
*   There is no release id featured in in Quick-Start. Is this intentional?
  *   Pgap.py –update progress is still too rapid (too many CR-terminated lines per second. There should be one line per second). I am only saying that because there was a ticket to fix that. If this is a feature of docker, that’s fine.
  *   Should we specify typical download times for ./pgap.py –update (which would be the fastest time for the fastest connection) in documentation? In my case, on current AWS pet, it took 9 ½ minutes.
  *   For MG37 CL you added -o parameter. In my opinion it’s better to qualify that as “…where -o parameter specifies the output directory”. It’s more direct. Current text requires mental work on behalf of the reader to match two mentions of mg37_results
  *   I did small obvious text fixes, feel free to review the commits (https://github.com/ncbi/pgap/wiki/Quick-Start/_history)
  *   MAJOR PROBLEM: Quick Start is not usable now: https://jira.ncbi.nlm.nih.gov/browse/PGAPX-408

**Comment by azat-badretdin** [comment]
MAJOR->*URGENT

From: Badretdin, Azat (NIH/NLM/NCBI) [E]
Sent: Wednesday, May 15, 2019 7:11 AM
To: ncbi/pgap <reply@reply.github.com>; ncbi/pgap <pgap@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [ncbi/pgap] Cannot access files on s3.amazonaws.com (#10)


  *   There is no release id featured in in Quick-Start. Is this intentional?
  *   Pgap.py –update progress is still too rapid (too many CR-terminated lines per second. There should be one line per second). I am only saying that because there was a ticket to fix that. If this is a feature of docker, that’s fine.
  *   Should we specify typical download times for ./pgap.py –update (which would be the fastest time for the fastest connection) in documentation? In my case, on current AWS pet, it took 9 ½ minutes.
  *   For MG37 CL you added -o parameter. In my opinion it’s better to qualify that as “…where -o parameter specifies the output directory”. It’s more direct. Current text requires mental work on behalf of the reader to match two mentions of mg37_results
  *   I did small obvious text fixes, feel free to review the commits (https://github.com/ncbi/pgap/wiki/Quick-Start/_history)
  *   MAJOR PROBLEM: Quick Start is not usable now: https://jira.ncbi.nlm.nih.gov/browse/PGAPX-408

**Comment by TheBigFatTony** [comment]
It still doesn't work:
```
$./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml
PGAP from branch : version 2019-05-13.build3740 is up to date.
/home/user/PGAP_docker/mg37_results
docker exited with rc = 1
```

**Comment by TheBigFatTony** [comment]
The problem was that I use Fedora. Distros like Fedora and CentOS have SElinux.

I could still run it by disabling SElinux temporarily. How?
`sudo setenforce 0`
Re-enable SElinux after using PGAP:
`sudo setenforce 1`

This is not a great option as it disables a security feature. The workaround for docker is to add :z to volume-mounts, as explained [here](https://docs.docker.com/storage/bind-mounts/#Configure%20the%20selinux%20label).

It would be nice if you could change your code to accommodate these systems, as many clusters run CentOS.

**Comment by slottad** [comment]
Thanks for doing the legwork! it didn't occur to me that the difference was SELinux, since we use CentOS for all of our work as well. Our Systems group must have turned it off, which is weird.

I have made the change to the code. The hard part was figuring out how to make it read-only and SELinux enabled at the same time (pro-tip, use a comma).

It is going through our testing before I push it to production, but in the meantime, you can try:

https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py

and see if that works for you.

**Comment by TheBigFatTony** [comment]
Thanks, that's great!
I'll test it soon and close the issue if it works.

**Comment by slottad** [comment]
Sorry! I forgot to edit the link after cut-n-paste! It is updated now. Here is the correct link again:

https://github.com/ncbi/pgap/raw/test/scripts/pgap.py

**Comment by TheBigFatTony** [comment]
I tried SElinux enabled + new pgap.py (/test/scripts/pgap.py) and SElinux disabled + regular pgap.py (raw/prod/scripts/pgap.py) on the MG37 test genome.

I started the process on my 16GB i7-8565U 1TB SSD laptop (Fedora 30). A short temporal summary:

07:28:01 - start
08:15:37 - last message in terminal ([step tblastn_wnode_2] start)
10:32:00 - last change to the annot.xxx-files. CPU-usage drops approximately at the same time.
11:00:00 (approx) - when I made the logs I'm sending to you
11:20 - still no change, I killed the process.

Download the `mg37_results` folder [here](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/29550/-6883849469882922296/publicLink/mg37_results.tar.xz). [This](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/29551/-1331281977928593760/publicLinkHtml/pgap_log.txt) is what I see in the terminal.

**Comment by slottad** [comment]
Dang, it was going along so well. At least we fixed the SELinux problem.

If you could please run it again with the `--debug`, and send us the new mg37_results folder, we will be able to see more of what is going on. It will have a debug subdirectory in it.

**Comment by TheBigFatTony** [comment]
Here you go: [Console](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/29567/-8874275987116895411/publicLinkHtml/pgap_log_debug.txt) log, [mg37_results](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/29568/-3876299585636511480/publicLink/mg37_results.debug.tar.xz) folder.

**Comment by TheBigFatTony** [comment]
I wanted to make sure that I had enough memory per CPU, so I edited pgap.py as follows:

```
❯ diff pgap.py pgap_limitcpus.py 
114c114
<         self.cmd = [params.dockercmd, 'run', '-i' ]
---
>         self.cmd = [params.dockercmd, 'run', '-i', '--cpuset-cpus', '0-3']
161c161
<         cmd = [self.params.dockercmd, 'run', '-i', '-v', '{}:/cwd'.format(os.getcwd()), self.params.docker_image,
---
>         cmd = [self.params.dockercmd, 'run', '-i', '--cpuset-cpus', '0-3', '-v', '{}:/cwd'.format(os.getcwd()), self.params.docker_image,
```

Although it worked and my resource monitor showed that only 4 out of 8 CPUs were used, the problem wasn't solved.

I'll post the logs anyway: [Console](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/29569/-8172290796019693287/publicLinkHtml/mg37_results.debug.4CPUs.tar.xz.txt) log, [mg37_results](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/29570/6128502653071569111/publicLink/mg37_results_debug.4CPUs.tar.xz) folder.

**Comment by slottad** [comment]
According to the logs you sent us, it looks like it worked before too, however the pgap.py program was exited early. The pgap.py program spawns the pipeline using Docker, and reports the output. If it is halted early, it doesn't necessarily halt the process in Docker.

We had this problem with a user who ran the process over an ssh session without using nohup, screen, or tmux. When the ssh session was disconnected, the pgap.py was halted, but not the pipeline.

**Comment by TheBigFatTony** [comment]
Yep, thanks for your help.
